---
# Deploy base stuff on all servers
- hosts: all
  remote_user: ubuntu
  sudo: yes
  roles:
   - common

- hosts: tag_app_zabbix
  remote_user: ubuntu
  sudo: yes
  roles:
   - zabbix

 - hosts: tag_app_megadiscourse
   remote_user: ubuntu
   sudo: yes
   roles:
     - discourse

# Discourse stuff
#- hosts: tag_app_discourse
#  roles:
#    - discourse

# znc stuff
#- hosts: tag_app_znc
#  roles:
#    - znc
