---
  - name: Create core team accounts
    user:
      name=leo
      group=sudo
      append=yes
    user:
      name=logan
      group=sudo
      append=yes
    user:
      name=mrz
      group=sudo
      append=yes
    user:
      name=tad
      group=sudo
      append=yes
    user:
      name=tanner
      group=sudo
      shell=/bin/zsh
      append=yes
    user:
      name=yousef
      group=sudo
      append=yes

  - name: Install ssh keys for core team
    authorized_keys:
      user=leo
      https://github.com/leomca.keys

    authorized_keys:
      user=logan
      key=https://launchpad.net/~logan/+sshkeys

    authorized_keys:
      user=mrz
      key=https://github.com/mzeier.keys

    authorized_keys:
      user=tad
      key=https://github.com/thomasfarrow.keys

    authorized_keys:
      user=tanner
      key=https://github.com/tannerfilip.keys

    authorized_keys:
      user=yousef
      key=https://github.com/flamingspaz.keys
