---
  - name: Create core team accounts
    dependencies:
      - { role: shells }

    user: name="{{ item.name }}" group=sudo append=yes shell="{{ item.shell }}"
    with_items:
      - { 'name':'leo', 'shell':'/bin/zsh' }
      - { 'name':'logan', 'shell':'/bin/bash' }
      - { 'name':'mrz', 'shell':'/bin/tcsh' }
      - { 'name':'tad', 'shell':/bin/zsh'}
      - { 'name':'tanner', 'shell':'/bin/zsh' }
      - { 'name':'yousef', 'shell':'/bin/zsh' }



# Stolen from http://companionway.net/2015/04/17/post1/ because it looks pretty sane
  - name: Install ssh keys for core team
    authorized_key: user="{{ item.user }}" key="{{ item.key }}"
    with_items:
      - { 'user':'leo','key':'https://github.com/leomca.keys' }
      - { 'user':'logan','key':'https://launchpad.net/~logan/+sshkeys' }
      - { 'user':'mrz','key':'https://github.com/mzeier.keys' }
      - { 'user':'tad', 'key':'https://github.com/thomasfarrow.keys'}
      - { 'user':'tanner','key':'https://github.com/tannerfilip.keys' }
      - { 'user':'yousef','key':'https://github.com/flamingspaz.keys' }

  - name: Copy sudoers for safety
    command: cp /etc/sudoers /etc/sudoers.tmp

  - name: Create sudoers.bak
    command: cp /etc/sudoers /etc/sudoers.bak

  - name: Ensure admin group is in sudoers with NOPASSWD
    lineinfile: "dest=/etc/sudoers.tmp state=present regexp='^%admin ' line='%admin ALL=(ALL) NOPASSWD: ALL' validate='visudo -cf %s'"
    register: sudoers_tmp_ok

  - name: Copy sudoers.tmp to sudoers
    when: sudoers_tmp_ok|success
    command: cp /etc/sudoers.tmp /etc/sudoers
